name: Ping website every 5 minutes

on:
  schedule:
    - cron: '*/3 * * * * '

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl target URL
        run: curl -s https://stat-h69u.onrender.com/
