name: Ping website

on:
  schedule:
    - cron: '*/13 * * * * '

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl target URL
        run: curl -s https://stat-h69u.onrender.com/
